
trigger:
- main

pool: 
  name: Azure Pipelines

variables: 
  - template: variables.yml

stages:
- stage: 'TestApplication'
  displayName: Testing Application in APIC
  jobs:
  - job: GetCredentials
    steps:
    - bash: |
        echo "##vso[task.setvariable variable=xAPIKey;isOutput=true]$(xapikey)"
        echo "##vso[task.setvariable variable=xAPISecret;isOutput=true]$(xapisecret)"
      name: credentials
  - deployment:  ResquestTestingAPI
    environment: $(environmentValue)
    pool: server
    timeoutInMinutes: 1
    cancelTimeoutInMinutes: 1
    dependsOn: GetCredentials
    variables:
      xapikey: $[dependencies.GetCredentials.outputs['credentials.xAPIKey']]
      xapisecret: $[dependencies.GetCredentials.outputs['credentials.xAPISecret']]
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/testing-api.yml
