
trigger:
- main

pool: 
  name: Azure Pipelines

variables: 
  - template: variables.yml

stages:
- stage: 'Testing'
  jobs:
  - job: GetCredentials
    steps:
    - bash: |
        echo "##vso[task.setvariable variable=xAPIKey;isOutput=true]$(xapikey)"
        echo "##vso[task.setvariable variable=xAPISecret;isOutput=true]$(xapisecret)"
      name: credentials
  - job: ResquestTestingAPI
    pool: server
    timeoutInMinutes: 1
    cancelTimeoutInMinutes: 1
    dependsOn: GetCredentials
    variables:
      xapikey: $[dependencies.GetCredentials.outputs['credentials.xAPIKey']]
      xapisecret: $[dependencies.GetCredentials.outputs['credentials.xAPISecret']]
    steps:
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'api Testing'
        method: 'GET'
        headers: |
          {
          "Content-Type":"application/json",
          "X-API-Key": "$(xapikey)",
          "X-API-Secret": "$(xapisecret)"
          }
        waitForCompletion: 'false'
